### ISSUE TITLE
"[Kingfisher] Failed to create CG context for blurring image."

### ISSUE THREAD

**Issue by nbortolussi** [onevcat/Kingfisher#565] opened 2017-01-18 21:54 UTC
I am getting this assertion causing my app to crash line 479 of Image.swift. In log the following error was also visible before the assertion: 

`
CGBitmapContextCreate: unsupported parameter combination: set CGBITMAP_CONTEXT_LOG_ERRORS environmental variable to see the details `

I have deleted the assertion and though I am not getting any blur, at least the app no longer crashes.

**Comment by onevcat** [comment] 2017-01-19 01:11
Hey.

It might be caused by some strange format of that image. May I know the image url (or the image itself) crashes your app? So I could have a look at what happen indeed.

Thanks.

**Comment by nbortolussi** [comment] 2017-01-19 14:42
Sure here is the image url: https://s3.amazonaws.com/winering-production/10906-313f1f875b62f3a-full

**Comment by onevcat** [comment] 2017-01-20 02:52
Should be fixed in #567.

There are some other work to do before a new version could be released. I will tag it later ASAP.

**Comment by anhhtbk** [comment] 2018-12-13 02:49
@onevcat Tomorrow I migrate Kingfisher to 5.0, after I received this bug.

**Comment by salyasev** [comment] 2019-02-04 20:54
Hello, I'm getting this issue on last Kingfisher 5.1.0

**Comment by Eldhopj** [comment] 2019-02-07 11:30
Same issue in here , while scrolling it getting crashed

**Comment by onevcat** [comment] 2019-02-07 15:56
@anhhtbk @salyasev @Eldhopj May I know what image causes this problem? Is there a link or an image I can use to reproduce this issue?

**Comment by seanliu1** [comment] 2019-02-18 20:13
I am facing the same issue while scrolling. However it only crashed when I use       
```

imageView?.kf.setImage(
            with: viewModel.thumbnailURL,
            placeholder: nil,
            options: [
                .processor(DownsamplingImageProcessor(size: imageView!.bounds.size)),
                .scaleFactor(UIScreen.main.scale),
                .cacheOriginalImage
            ])
```

**Comment by Eldhopj** [comment] 2019-02-19 12:48
@onevcat 
crash happens when the imageview size is zero also

**Comment by onevcat** [comment] 2019-02-25 13:40
@seanliu1 Not quite sure about it. The image itself seems fine.

Is there any crash log for it?

@Eldhopj The crash of `DownsamplingImageProcessor` for zero or negative size should be already fixed in #1074, can you confirm that you are using the latest version?

**Comment by seasox** [comment] 2019-04-25 09:33
This problem also occurs when using ResizingImageProcessor with a referenceSize of CGSize.zero

**Comment by onevcat** [comment] 2019-12-01 03:05
The `ResizingImageProcessor` should be failing with an `assertionFailure`, which is intended as a warning of incorrect usage of this API. It behaves as a reminder when developing, and will not crash in a release build.

**Closed by onevcat** 2019-12-01 03:05 UTC

**Comment by Doramical** [comment] 2021-02-03 12:21
I received this bug in Kingfisher 6.0 with follow images:

![1](https://user-images.githubusercontent.com/9795720/106709153-0e0a8a80-662f-11eb-8bd5-21aff9a02dc3.gif)
![2](https://user-images.githubusercontent.com/9795720/106709165-1236a800-662f-11eb-9074-46ec3dd76e4e.gif)
