### ISSUE TITLE
calling retrieveImageInDiskCache method cost quite a lot memory and made the app get killed 

### ISSUE THREAD

**Issue by fans3210** [onevcat/Kingfisher#730] opened 2017-07-19 04:59 UTC
### Issue Description

Here is my usecase:

I have a page vc with several pages, each one contains a collectionview for showing images like a gallery. I manually handles the image downloading and caching because the requirement from my customer is: every image should be editable when the page was shown. Customer doesn't like the loading bar appeared in the image preview/editing page.  So I cannot use imageview.kf.xxx for my case. I have to show the page only after all images finished downloading and caching. My cache key is just the remoteurl.

For retrieving images, my method is also very straight forward: 
1. check if images are cached
2. if in memory cache, call retrieveImageInMemoryCache(forKey:) and return
3. if in disk, call cache.retrieveImageInDiskCache(forKey:) instead

Everything was fine at first after images just finished downloading. Since they are in 'kf memory cache' after downloaded, retrieveImageInMemoryCache would be called if I want to get the image and set it in the imageview. The total memory cost was not that much and was less than 100Mb. 

The nightmare comes when the app got relaunched. As we see, if app relaunched, the memory cache was empty at first so the 'retrieveImageInDiskCache' method was called instead and memory cost was increasing horribly fast(but memory cache still empty because the images are in memory not kingfisher's memory cache). The app will be killed when the memory cost increased to 2gb. I also tried calling 'clearAllMemoryCache' method but of course it won't work since the images are just in memory, not 'kf memory cache'. 

I'm not sure whether this is my own prob or a bug for now. I'm still investigating on this. I would be very appreciated if you could give me some help or suggestions. Thank you.

**Comment by onevcat** [comment] 2017-07-19 05:13
Not sure what happened. The `retrieveImageInDiskCache` just getting the data from the cached files from disk, so it should not take such a huge amount of memory, unless you are trying to loading quite a lot of high resolution images. What's the size of your image? Could it be the problem?

And it would be great if I could have a sample project which can reproduce this.

**Comment by fans3210** [comment] 2017-07-19 05:56
Yes it's about a total number of 30 of high resolution images. When they are in 'kf mermory cache', the total size consumed is about 20mb. But when they are loaded from disk cache, they consume more memory storage: more or less 200mb - 10 times of the cost of 'kf memroy cache'. I will provided a sample project later for this issue

**Comment by onevcat** [comment] 2017-07-19 07:36
It could happen if you are trying to decode the images. Take care when the images are set to image views or [decoded in background](http://onevcat.github.io/Kingfisher/Enums/KingfisherOptionsInfoItem.html#/s:FO10Kingfisher25KingfisherOptionsInfoItem16backgroundDecodeFMS0_S0_), since they will take full size of the raw pixel data.

Instead of showing 30+ full resolution images in image views, I suggest to just display thumbnails (you don't have such big screen for them on a mobile) and only load the full version when needed (maybe in a detail view controller).

But if you are doing the same loading operation, it could be strange. And also the images should be released instead of keeping increase, which means you have something leaking in your code. 

I'd quite like to check it deeper once there is a sample for it.

**Comment by fans3210** [comment] 2017-07-19 09:41
Sorry @onevcat . After setup a new project and tested, I found that the leaking issue is my own problem. Sorry about this. Although retrieveImageInDiskCache cost more memory compared to retrieveImageInMemoryCache, all images still got released when the vc disappeared. 

So, for my issue. I will use thumbnails for collectionview cells and resolve the leaking prob. Sorry again for my own fault and thanks a lot for your patience!

**Closed** 2017-07-19 10:19 UTC
