### ISSUE TITLE
Image not being properly rotated if ImageProcessor is applied

### ISSUE THREAD

**Issue by nbortolussi** [onevcat/Kingfisher#535] opened 2016-12-08 15:59 UTC
My image appears with the correct orientation with no processor applied. However, when a BlurProcessor is added to the image, the processor works correctly but the image is no longer rotated as it should be:

```let processor = BlurImageProcessor(blurRadius: 8)
        backgroundImage.kf.setImage(with: image, placeholder: nil, options: [.processor(processor)])

**Comment by onevcat** [comment] 2016-12-14 02:12
Umm..The `BlurProcessor` (as well as all of other processors) does not do anything on the orientation. Maybe you could implement a processor your own to normalize the image, if you need to display an image with different orientation settings. There is a `kf.normalized` property you could use for it.

The final processor might be something like this:

```swift
struct NormalizingProcessor: ImageProcessor {
    let identifier = "normalized"
    func process(item: ImageProcessItem, options: KingfisherOptionsInfo) -> Image? {
        switch item {
        case .image(let image):
            return image.kf.normalized
        case .data(_):
            return (DefaultImageProcessor() >> self).process(item: item, options: options)
        }
    }
}

let p = BlurImageProcessor(blurRadius: r) >> NormalizingProcessor()
imageView.kf.setImage(with: URL(string: ""), options: [.processor(p)])
```

**Comment by nbortolussi** [comment] 2016-12-14 19:14
If it is the case that the processors do not affect rotation at all then not sure why image.kf.setImage(with: image) and  image.kf.setImage(with: image, placeholder: nil, options: [.processor(processor)]) gives different rotation results?

Anyway your recommendation with normalize did do the trick - thanks!

**Comment by onevcat** [comment] 2016-12-20 01:44
It is due to the cgImage based filter. I will give it a better fix now.

**Comment by onevcat** [comment] 2016-12-20 02:20
Fixed in 3.2.3.

**Closed by onevcat** 2016-12-20 02:20 UTC

**Comment by lastcc** [comment] 2017-08-27 10:14
@onevcat Hi again.

I am using the latest version of KingFisher, and the image is not correctly displayed. Is there a way to fix this? Because the above post mentioned that this was fixed  in 3.2.3.

The code snippet that I am using:
```swift
imageView.kf.setImage(with: asset.fileURL, placeholder: asset.transientImage, options: [.backgroundDecode])
```

After the transformation of an UIImage object to PNG Data object, the `open var imageOrientation: UIImageOrientation` information is lost forever.

So, set the image to UIImageView, the image is correctly displayed.

But after the data is persisted on disk and load again by KingFisher, the orientation is wrong. 

See [this](https://stackoverflow.com/questions/3554244/uiimagepngrepresentation-issues-images-rotated-by-90-degrees), and [this](https://stackoverflow.com/questions/7838699/save-uiimage-load-it-in-wrong-orientation).

**Comment by onevcat** [comment] 2017-08-27 12:58
@lastcc 

As mentioned in your ref links, there is no exif information in a PNG file, so the rotation info in a JPEG will be lost in a PNG representation. I tried JPEG with non-unified orientation in latest Kingfisher and it works well in both loading from web or cache. (I was using this image: https://github.com/recurser/exif-orientation-examples/blob/master/Landscape_2.jpg for testing).

If you are loading a JPEG with problem, may I know the image url so I could have a deep look into it.

**Comment by lastcc** [comment] 2017-08-28 04:55
@onevcat oh sorry I mean I have problems with PNGs. I think I may address my problem by passing an custom RotateProcessor to the method.

I was misunderstanding this GitHub issue, and thought it had something to do with processors. Since I also used blur. Turns out the problem is on my side.
