### ISSUE TITLE
7.0 Xcode13 Archive error

### ISSUE THREAD

**Issue by PCBZ** [onevcat/Kingfisher#1931] opened 2022-04-11 03:05 UTC
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/15225052/162658362-aa499e9f-5b78-4399-9564-964f97db4698.png">
Xcode13 archive error with 7.0

**Comment by onevcat** [comment] 2022-04-11 04:12
May I know what is your target when performing this? `GraphicsContext` is a type inside Kingfisher and now I've no idea why this is happening now. 

Is it possible to create a minimal sample project in which this can be reproduced?

**Comment by PCBZ** [comment] 2022-04-11 06:37
Pls wait, I'll try it again. All what I can tell u now is: 1. We r using Xcode13.3; 2. We r using the latest 7.1.2 KF.

**Comment by PCBZ** [comment] 2022-04-11 07:10
`platform :ios, '12.0'
use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target '*****' do
  # Pods for NowCRM
  pod 'LookinServer', :configurations => ['Debug']
   pod 'GoogleSignIn'
   pod 'Firebase/Auth'
   pod 'Firebase/Analytics'
   pod 'Firebase/Crashlytics'
   pod 'UITextView+Placeholder'
   pod 'RadioButton'
   pod 'Moya/RxSwift'
   pod 'DateToolsSwift'
   pod 'MaterialComponents/TextFields'
   pod 'MaterialComponents/Buttons'
   pod 'MaterialComponents/Chips'
   pod 'MaterialComponents/Snackbar'
   pod 'RxCocoa'
   pod 'Popover'
   pod 'DZNEmptyDataSet'
   pod 'Action'
   pod 'RxDataSources'
   pod 'SwiftLint'
   pod 'AnyCodable-FlightSchool'
   pod 'Charts'
   pod 'FSCalendar'
   pod 'IQKeyboardManagerSwift'
   pod 'Kingfisher', '~> 7.0'
   pod 'lottie-ios'
   pod 'MBProgressHUD'
   pod 'ESPullToRefresh'
   pod 'SnapKit'
   pod 'CropViewController'
   pod 'FDWaveformView'
   

   target '***Tests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxBlocking'
    pod 'RxTest'
  end
end`

the podfile is like that.

**Comment by jakernodle** [comment] 2022-05-03 12:52
Any update here? I'm having a similar issue

**Comment by ValeriiVV** [comment] 2022-05-06 13:37
Yes, sorry, I had old version of Kingfisher (6.3.1). I've updated cocoa, download new version Kingfisher 7.2.1 and it works fine.

**Comment by PCBZ** [comment] 2022-05-07 02:31
I have found the reason. It is a cocoapod bug maybe, the GraphicContext file did NOT checkout, I fixed it with reinstall it. @onevcat All our Macs encountered this problem. Can u check this situation, checkout the KF 6.*, and update it to KF 7.*, with the latest Xcode version.

**Comment by onevcat** [comment] 2022-05-07 09:00
@PCBZ Did you try `pod update Kingfisher` instead of a merely `pod install`? `pod install` will just look into the lock file and use the versions there, so it means your installation is still using the old v6 versions.

Although it is possible for you to remove the lock file totally and do installation again.

Since it is not likely an issue in Kingfisher. I am closing it now.

**Closed by onevcat** 2022-05-07 09:00 UTC
