### ISSUE TITLE
Firebase storage URL returns  403 error for Kingfisher but works for URLSessionDataTask

### ISSUE THREAD

**Issue by MadGeorge** [onevcat/Kingfisher#1433] opened 2020-04-17 12:28 UTC
I have image located on Firebase Storage at url:  
https://firebasestorage.googleapis.com/v0/b/testingtools-e201f.appspot.com/o/tmp%2FuceEv9VO.png?alt=media

Rules of the storage allows to read this object without authentication token. You can check it just by clicking at the url. 

When i try to load it with Kingfisher no image is returned, and error object says 403, forbidden:  
```swift
import Kingfisher

...
imageView.kf.indicatorType = .activity
let processor = RoundCornerImageProcessor(cornerRadius: cornerRadius)
imageVIEW.kf.setImage(with: URL(string: url), placeholder: nil, options: [.processor(processor)]) { (image, error, _, url) in
    // image is nil and error 403, forbidden
}
```

But, the same url in same place will load image data without any errors:  
```swift
let _processor = RoundCornerImageProcessor(cornerRadius: cornerRadius)
URLSession.init(configuration: .default).dataTask(with: URL(string: url)!) { (data, res, _) in
    if let d = data {
        DispatchQueue.main.async {
            if let cgi = _processor.process(item: .data(d), options: [])?.cgImage {
                // No errors
                self.imageVIEW.image = UIImage(cgImage: cgi)
            }
         }
     }
 }.resume()
```
Any ideas how it's possible? I think Kingfisher use URLSession underneath, how it may be different in terms of data loading?

**Comment by onevcat** [comment] 2020-04-18 08:57
I can download and show the image without any problem in the sample app.

I noticed that you are using a very old callback style for Kingfisher `setImage`. What is the version you are trying?

**Comment by MadGeorge** [comment] 2020-04-19 08:04
@onevcat thank you for the answer. We froze Kingfisher to '4.10.1'. This might be the reason for such strange behaviour. I will talk to my team to consider to upgrade to the latest version of the lib. Thank you.

**Comment by onevcat** [comment] 2020-04-19 08:06
I am now closing it since I cannot reproduce this issue.

Please reopen it if you still have the problem with the new version. Good luck!

**Closed by onevcat** 2020-04-19 08:06 UTC
