### ISSUE TITLE
Cant show this picture

### ISSUE THREAD

**Issue by ChildProdigy** [onevcat/Kingfisher#2286] opened 2024-09-13 01:19 UTC
http://www.goodnews.org.tw/favicon.ico

I see that the data is loaded correctly but not displayed.
It should be a problem with IOS itself,
because native components also have display problems.

**Comment by onevcat** [comment] 2024-09-30 13:46
Yes...It seems that the IDAT chunk is not properly set in the file. At least the ImageIO shipped by macOS and iOS cannot read it correctly.

> handle_write_error:113: zlib error
> imagePNG_write_error_break:90: *** ERROR: imagePNG_write_error_break
> handle_write_error:113: No IDATs written into file 

Since I can confirm loading of some other ico file (such as [this](https://raw.githubusercontent.com/microsoft/Windows-classic-samples/refs/heads/main/Samples/Win7Samples/netds/wlan/WirelessHostedNetwork/HostedNetwork/res/computer.ico)) is properly done, so it is more likely a malformed image.

I am closing this issue.

**Closed by onevcat** 2024-09-30 13:46 UTC
