### ISSUE TITLE
Cant load image using URL while offline with cache - hits failure block every time (NSURLErrorDomain Code=-1009)

### ISSUE THREAD

**Issue by LiamLaverty5** [onevcat/Kingfisher#1509] opened 2020-09-15 13:39 UTC
I am trying to allow an image to be loaded on a view controller that is loaded when the app is first opened. When I load the application with internet connection, the image loads fine. 

If i run the app with no internet, the kf.setImage fails and the following is returned: 

> A URL session error happened. The underlying error: Error
> Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to
> be offline." UserInfo={_kCFStreamErrorCodeKey=50,
> NSUnderlyingError=0x281639620 {Error Domain=kCFErrorDomainCFNetwork
> Code=-1009 "(null)" UserInfo={_kCFStreamErrorCodeKey=50,
> _kCFStreamErrorDomainKey=1}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <F8F764A2-A96C-4B44-B237-DCF1CB07573A>.<10>,
> _NSURLErrorRelatedURLSessionTaskErrorKey=(
>     "LocalDataTask <F8F764A2-A96C-4B44-B237-DCF1CB07573A>.<10>" ), NSLocalizedDescription=The Internet connection appears to be offline.,
> NSErrorFailingURLStringKey=https://athlete-series-media-bucket-development.s3.eu-west-1.amazonaws.com/user/c6990e17-48cd-4197-870b-ca8236e48c69/avatar/c6990e17-48cd-4197-870b-ca8236e48c69.png,
> NSErrorFailingURLKey=https://athlete-series-media-bucket-development.s3.eu-west-1.amazonaws.com/user/c6990e17-48cd-4197-870b-ca8236e48c69/avatar/c6990e17-48cd-4197-870b-ca8236e48c69.png,
> _kCFStreamErrorDomainKey=1}

I have used this code for loading images offline before and used the code below and it works fine. If I terminate the app, switch internet off, reload the app, the picture should display. Currently, it just displays the placeholder. 

Code to set UIImageView:

   ```
 if let url = user.profileImage?.imageUrl {
                            let url = URL(string: url)
                            let processor = DownsamplingImageProcessor(size: self.userImg.bounds.size)
                                |> RoundCornerImageProcessor(cornerRadius: 20)
                            self.userImg.kf.indicatorType = .activity
                            self.userImg.kf.setImage(
                                 with: url,
                                 placeholder: UIImage(named: "Avatar"),
                                 options: [
                                     .processor(processor),
                                     .scaleFactor(UIScreen.main.scale),
                                     .transition(.fade(1)),
                                     .cacheOriginalImage
                                 ])
                             {
                                 result in
                                 switch result {
                                 case .success(let value):
                                     print("Task done for: \(value.source.url?.absoluteString ?? "")")
                                     
    
                                    // From where the image was retrieved:
                                    // - .none - Just downloaded.
                                    // - .memory - Got from memory cache.
                                    // - .disk - Got from disk cache.
    
                                    // The source object which
                                    
                                 case .failure(let error):
                                     print("Job failed: \(error.localizedDescription)")
                             }
                        }

```
The code enters the failure block when the app is ran with no internet. I have used this code on previous projects and it successfully displays with no internet, however something is wrong on this instance. Any help would be appreciated.

#### Reproduce
Open application with internet, image loads fine. 
Close application & turn internet off.
Open application.
Note image does not display (only placeholder will)

**Comment by LiamLaverty5** [comment] 2020-10-05 13:32
.

**Comment by onevcat** [comment] 2020-10-05 14:21
I cannot reproduce this issue, or at least cannot reproduce it 100%. Did you try it on all your devices/simulators and are they all the same?

In Kingfisher, the download images will be sent to a disk cache. As its name indicates, it is just a cache version of the image. That means, there is no guarantee that these files are always there and prepared to use. Kingfisher puts these downloaded image data to your app's cache folder, which managed by the system. So besides the disk cache rules defined by Kingfisher (maximum size and expiration duration), the system also reserves the right to purge it at the proper time (that usually happens when you do not have enough storage on the disk). In this case, the iOS system would just delete these cached files without notifying your app or Kingfisher. The only way to retrieve them back is by loading from the Internet.

If you can reproduce it on all your devices, including on those devices with enough disk storage. That might be related to the cache key you are using. By default, Kingfisher determines the cache key by composing the URL and the processor it is using. If you are sure that the URLs are not changing during different app sessions, you can try to print out the `processor.identifier` before setting the image, to see if it is the same.

**Comment by LiamLaverty5** [comment] 2020-10-07 08:29
@onevcat I found the problem. When first loading online, the image is never cached / stored on the disk or memory.. When debugging, before loading the image initially, the cache memory storage contains 9 items, disk storage "maybeCached" is the same. 

Is there a way to increase the default size for this so that when loading this image initially it can be stored? Or is that the upper limit reached for this cache system? Thanks


![Screenshot 2020-10-07 at 09 26 16](https://user-images.githubusercontent.com/44978890/95306597-8464cf00-087f-11eb-8d77-f837cf87197e.png)

**Comment by onevcat** [comment] 2020-10-07 08:53
Yes. There is no size limitation of disk cache by default. And it (`sizeLimit = 0`) is also no limitation in according to your config.

I want to declare some fact (and implementation detail) for you:

1. The `maybeCached` is a shortcut to check image in disk cache, to reduce disk I/O. As its name suggested, it does not mean exactly the count of images in the cache.
2. If you are setting the break point and show the cache result in the completion handler for a single image, it is possible that you cannot get the correct result. Writing to disk cache happens in a background thread and the setting image completion handler would be called earlier than the image actually written to cache. To inspect a more correct result, try to add the `.waitForCache` option when setting the image.
3. For debugging purpose, you can try to use the `imageCachedType(forKey:processorIdentifier:)` method to check the cache state of an image. As my last reply, I strongly suspect that you are having a different URL or processor identifier every time so the cache is not retrieved. So please make sure to compare the URL and processors to make sure the cache keys are the same on each load for the image.

```swift
if let url = user.profileImage?.imageUrl {
    let url = URL(string: url)
    let processor = DownsamplingImageProcessor(size: self.userImg.bounds.size)
        |> RoundCornerImageProcessor(cornerRadius: 20)
    print("URL: \(url.absoluteString)")
    print("Processor Id: \(processor.identifier)")
```

If these are not identical, it means you are not trying to seek the image under the same key.

And to confirm the cache type of an image:

```swift
ImageCache.default.imageCachedType(forKey: url.absoluteString, processorIdentifier: processor.identifier)
```

Before you load it for the first time, it should be `.none`. After loading, it should be `.memory`. And after a reboot of the app (and before loading it again), it should be `.disk`.

**Comment by onevcat** [comment] 2020-10-07 08:54
For adjust the cache config (although I don't think it is your case), check the wiki page below, and all related classes.

https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet#set-limit-for-cache

**Comment by LiamLaverty5** [comment] 2020-10-07 09:46
@onevcat I can narrow it down to the limiting issue because this cache implementation with the user profile image works fine on fresh/new accounts on the application, I.E. accounts with not much "Sessions" with images stored on the cache..

I debugged thoroughly and the processor ID & url absolute string are the same each time. I added the .waitForCache option and when confirming the type of cache for the image using
` ImageCache.default.imageCachedType(forKey: url.absoluteString, processorIdentifier: processor.identifier)
`

- On first initial load, before setting image, cacheType is **none**
- In completion block of `setImage`, cacheType is **memory**
- After reboot of app, before setting image again, cacheType is **none** again
- In completion block of loading the second time, cacheType is **memory**

**Note that, sometimes after rebooting of the app, within the completion block of setting the image successfully, cacheType is occasionally **none**

And so on.. It never reaches the disk, and even sometimes fails to write to memory -> which I am attributing to storage issues.. 

Therefore, how would you go about debugging / attempting to increase the size of memory / disk cache, beyond the default **no limit** that is configured automatically? 

Thanks

**Comment by onevcat** [comment] 2020-10-07 10:35
Hmmm,

That is interesting. I tried exactly your code, and it runs well and I can get the desired result:

![截屏2020-10-07 19 21 21](https://user-images.githubusercontent.com/1019875/95319069-607ea900-08d2-11eb-8bb4-8c0f348fad35.png)

The cache itself is totally optional when setting the image, so it does not give back the error directly. So if you want to debug this, you may need to set a breakpoint on the line to see if there is a disk error or not. It is easy if you are using CocoaPods or SPM, but might be tricky if you are using Carthage.

https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/ImageCache.swift#L398

Another (maybe) easier way would be manually calling the store method, and check the cache result which it returns. Maybe do it in the setting image completion handler:

```swift
imageView.kf.setImage(/*...*/) { result in
    switch result {
    case .success(let value):
        ImageCache.default.store(value.image, forKey: url.absoluteString, options: .init([.processor(processor)])) { r in
            print(r)
        }
    //...
}
```

to check if both the memory cache and disk cache is giving you the `.success` result.

By the way, can I get one of the image URL or the image itself which you are using? I want to also make sure it is not related to some of the data issues or so.

**Comment by onevcat** [comment] 2020-10-07 10:38
By default, the memory cache size limit is set to 25% of your device total memory, and the disk cache can take unlimited space. So it should be a really rare case that your disk cache fails unless the device is about to be out of disk storage itself.

Adjusting the config like that might not help IMO.

**Comment by LiamLaverty5** [comment] 2020-10-07 11:55
@onevcat Yes, that code works for me also, just not on this one specific account / instance of the iOS application, due to what I believe is being caused by the number of stored images in the cache already due to synced "sessions"..

Using 
```
ImageCache.default.store(value.image, forKey: url.absoluteString, options: .init([.processor(processor)])) { r in
            print(r)
        }
```
In the success block returns:

- On first initial load, r = `**CacheStoreResult(memoryCacheResult: Swift.Result<(), Swift.Never>.success(), diskCacheResult: Swift.Result<(), Kingfisher.KingfisherError>.success())**`

- In completion block, `**cacheType is **none****`

- After reboot of app, r = `**CacheStoreResult(memoryCacheResult: Swift.Result<(), Swift.Never>.success(), diskCacheResult: Swift.Result<(), Kingfisher.KingfisherError>.success())**`

- In completion block of loading the second time, cacheType is **memory**

- After reboot of app the third time, r = **`CacheStoreResult(memoryCacheResult: Swift.Result<(), Swift.Never>.success(), diskCacheResult: Swift.Result<(), Kingfisher.KingfisherError>.success())`**
- cacheType is **memory**


Image being used can be seen here, although like I said before, this functionality works fine on this application when I login with an account that has no previous cached images (i.e. no synced *session*) -> _[](https://athlete-series-media-bucket-development.s3.eu-west-1.amazonaws.com/user/c6990e17-48cd-4197-870b-ca8236e48c69/avatar/c6990e17-48cd-4197-870b-ca8236e48c68.png)_

I have attempted this on numerous devices with 10GB+ free and even on fresh iOS simulators and the same thing occurs. The issue definitely lies within the limit on the cache / the image not being stored in memory/disk to enable it to be loaded offline, due to some sort of restriction / constraint / blocker.. 

Do you have any other recommendations on ways to debug? It is clear from that "r" result that it is never being cached? 

Thanks

**Comment by onevcat** [comment] 2020-10-07 12:17
No idea about what is happening now.

I need a reproducible sample to dig into but currently, there seems to be no way for me to reproduce it, so it is quite hard for me to say what can be wrong.

The image seems quite normal and can be cached on disk without a problem. So it is definitely related to a certain use case.

You mentioned some "no synced sessions" and "synced sessions". What do you mean by that?

Or is it possible that you can create a minimal sample project in which this can be reproduced? So I can start to look at it sooner.

Thanks!

**Comment by LiamLaverty5** [comment] 2020-10-07 13:12
@onevcat 
What could you take from the cache store results? I.E. the print statements of r? It is clearly failing to save here right?

Basically the application is for syncing sport sessions, and viewing the sessions of that. Therefore, an account with many sessions, each having an image attached to them, will have more cache used up. 

When I test with a fresh account, I.E. no session images or only a few session images taking up space in the cache, it functions fine as it should. Saves to disk and then works offline. However, when I test with an account that has many sessions (I.E. 30+), each having a session image stored in the cache, the cache saving function does not work.

I may be able to produce a sample for you to see the problem but I will have another play about with config settings / freeing up some storage in the cache / not storing all session images here and see if I can resolve this..

Thanks for looking into it!

**Comment by onevcat** [comment] 2020-10-07 13:31
> What could you take from the cache store results? I.E. the print statements of r? It is clearly failing to save here right?

If failing, the `ImageCacheResult` value will contain the error information. But in your case, it is always printing success, so the disk cache was done without a problem.

For the session, I now know what you were talking about. If you are on the simulator which can also reproduce it, I guess you can just open the Cache folder of the app (You can find the device on your mac in the folder of `ImageCache.default.diskStorage.directoryURL`). Open it with Finder, and inspect how the disk cache file changes. Maybe there is a case that the cache gets purged by the system.

After all, as my first reply indicated, the cache **DOES NOT guarantee** the persistence of images (as the AppStore review guideline, these content which can be redownloaded should be put as cache), and your logic should not rely on the images always existing.

If you can ensure that the issue is due to the purging behavior of the system, but you still need the offline access, a possible way might be using [this init method](https://github.com/onevcat/Kingfisher/blob/master/Sources/Cache/ImageCache.swift#L235) to create your own cache in the Document folder, and then assign it to the [`KingfisherManager.default.cache`](https://github.com/onevcat/Kingfisher/blob/master/Sources/General/KingfisherManager.swift#L85) for future use. But I personally do not recommend doing so, which leads to a risk of rejecting in the review.

**Comment by LiamLaverty5** [comment] 2020-11-06 09:09
@onevcat I was eventually able to find the issue.. The cached images were being wiped after being stored initially as there was a call to `cache.clearMemoryCache()` and `cache.clearDiskCache()` hidden deep within the code.. This was a project I inherited so apologies for the misunderstandings!

Thanks for all your help, the library is great! This can be closed now.

**Comment by onevcat** [comment] 2020-11-06 14:24
Never mind! Glad to hear that you have found what is going on!

**Closed by onevcat** 2020-11-06 14:24 UTC
