### ISSUE TITLE
Fatal Error in prefetcher

### ISSUE THREAD

**Issue by mihaibulic** [onevcat/Kingfisher#316] opened 2016-05-10 04:03 UTC
I use the ImagePrefetcher to cache photos before I need them, so I frequently start and stop 2 prefetchers with several photos.

I occasionally run into a problem:  Fatal Error: Can't form Range with end < start
at this line in ImagePrefetcher.downloadAndCacheResource(resource: Resource):

`let pendingResources = self.prefetchResources[self.requestedCount..<self.prefetchResources.count]`

Is it that stop() was called on the prefetcher and a downloadTask is trying to stop itself, but it's actually already done (e.g requestedCount == prefetchResources.count)?

(also thanks for making this library, aside from this crash, it's great)

**Comment by onevcat** [comment] 2016-05-10 04:48
@mihaibulic Thanks for letting me know it.

May I know the number of images you are trying to fetch as well as the `maxConcurrentDownloads` you are using? It might be help for me to track what happens.

Thanks!

**Comment by mihaibulic** [comment] 2016-05-10 04:56
I have 2 separate prefetchers, never prefetching more than 3 images.  I don't change maxConcurrentDownload from the default

**Comment by mihaibulic** [comment] 2016-05-13 00:07
@onevcat, any word on this?

**Comment by onevcat** [comment] 2016-05-13 01:49
Hi, @mihaibulic 

I checked it and failed to reproduce your issue.

For you case, since you were only prefetching 3 images, the requested count should be always the same as prefetchResources.count. It will produce an empty slice and should not lead a crash.

I am now not sure what could lead the requested count be larger than the total resource count. Could you reproduce this error in a good way, or even better supply a simple demo so I could dig it deeper?

**Comment by mihaibulic** [comment] 2016-05-13 02:43
Hey @onevcat,

unfortunately it's not deterministic.  The only thing I have noticed is that once it starts to occur, it continues to occur.

Here is what I'm (basically) doing:

```
private let PREFIX = "https://storage.googleapis.com/spree-photo-storage/photos/1080x1920-"
private let SUFFEX = ".jpg"
private let IDS = [
    "0000a635-b38c-4521-bded-fdc173d884b2",
    "000130c9-884f-489e-a5f2-65e7ec1066fc",
    "000140b2-5f09-4845-90c2-0e2a56109243"
]

private var currentPrefetched : ImagePrefetcher?

/**
This function is generally called every 30 seconds, but may be called back-to-back
*/
private func prefetch(photoIds: [String]) {
    currentPrefetcher?.stop()
    var prefetchUrls : [NSURL] = []

    for id in photoIds {
        if let urlNotNil = generateURL(photoId) {
            prefetchUrls.append(urlNotNil)
        }
    }

    currentPrefetcher = ImagePrefetcher(urls: prefetchUrls)
    currentPrefetcher?.start()
}

/**
This function may be called at anytime, even immediately before or after prefetch is called with the same photoId
*/
private func loadPhoto(photoId: String, decache: Bool = false) {
    guard let urlNotNil = generateURL(photoId) else {
        return
    }

    KingfisherManager.sharedManager.retrieveImageWithURL(
                urlNotNil,
                optionsInfo: nil,
                progressBlock: nil,
                completionHandler: {(image: Image?, error: NSError?, cacheType: CacheType, imageURL: NSURL?) -> () in
                    if error != nil || image == nil {
                        self.fail(photoId)
                    } else {
                        self.setImage(image, photoId: photoId, loadTime: (CACurrentMediaTime() - startTime))
                        if decache {
                            KingfisherManager.sharedManager.cache.removeImageForKey(urlNotNil.absoluteString)
                        }
                    }
                })
}

private func generateURL(photoId: String) -> NSURL? {
   return NSURL(PREFIX + photoId + SUFFIX)
}
```

**Comment by onevcat** [comment] 2016-05-13 03:27
Thanks! It could help.

I will take a second look at it later and let you know if there is any progress.

**Comment by onevcat** [comment] 2016-05-13 03:33
And for a first glance now, I guess it could be a problem of using the same downloader for both the prefetcher and retrieveImageWithURL.

Would you please try to pass an option to the image prefetcher to specify another downloader to see whether the issue still being there?

You could do that by changing the line 

```swift
currentPrefetcher = ImagePrefetcher(urls: prefetchUrls)
```

to

```swift
currentPrefetcher = ImagePrefetcher(urls: prefetchUrls, optionsInfo: [KingfisherOptionsInfoItem.Downloader(ImageDownloader(name: "downloader"))])
```

**Comment by mihaibulic** [comment] 2016-05-13 23:53
I've changed those lines, I'll see if it happens again (like I said it's not deterministic or even easy to repro, so it might take a while)

@onevcat, Should I be using different downloaders for each prefetcher (I have 2)?

**Comment by onevcat** [comment] 2016-05-14 00:30
It would be better to do so. Since the downloader will count up and combine all tasks with the same URL, so there could be a chance that even you called `stop` on the prefetched, but there are some other downloader (or prefetcher) is requiring this resource. So the download progress might not be stopped as expected.

Using standalone downloader for each prefetcher would be a more safer way here.

If this could solve your issue, I will switch to a new created inner downloader for each new prefetcher, so this potential issue could be solved completely.

**Comment by mihaibulic** [comment] 2016-05-14 00:36
Thanks for the quick responses @onevcat 

I'll let you know if I see more issues

**Comment by mihaibulic** [comment] 2016-05-16 20:30
Hey @onevcat, still seeing the issue.

Could this be problematic:
-create and start a prefetcher with url X
-immediately after, call retrieveImageWithURL with the same url X

Also what about this::
-create a prefetcher with url X
-create another prefetch, also with url X
-stop the initial prefetcher
-stop the 2nd prefetcher
(I was thinking that calling stop() on the 1st prefetcher would cancel the downloading of the image at url X in both prefetchers and would cause issues when trying to stop the 2nd prefetcher?)


I could try not calling stop on the prefetcher and just letting it run its course, that should technically fix the crash, right?

**Comment by onevcat** [comment] 2016-05-17 02:48
Hi, @mihaibulic 

It could be a problem if you are using the same downloader for multiple prefetchers and retrieve method (the retrieve method is using a default downloader if you do not specify one). 

A downloader in Kingfisher will count the download request sent for a same URL, if the downloading for that URL is already there, it will prevent the later requests. The same thing happens when you try to stop a download: if the task count for a URL is not 0, it means there are still some other task waiting for the download, so it will not be stopped.

For both cases you described, if you are using different downloaders, the two downloading processes should be independent. Calling stop on a prefetcher should have nothing to do with another one, they do not share state each other (unless you are using the same downloader).

I will try to build a demo to see how can I regenerate this problem later today, and let you know if there is any progress.

**Comment by mihaibulic** [comment] 2016-05-17 22:20
I create prefetchers in 2 different classes, and I use a different downloader for each of the different classes, but within those classes I do reinstantiate the prefetchers frequently (everytime with the same downloader).  Should I create a new downloader everytime I reinstantiate the prefetcher, like so:

currentPrefetcher = ImagePrefetcher(urls: prefetchUrls, optionsInfo: [KingfisherOptionsInfoItem.Downloader(ImageDownloader(name: "classname \(CACurrentMediaTime())"))])

**Comment by onevcat** [comment] 2016-05-18 05:21
It is worthy to try that, using different downloader instead of reusing a previous one.

Especially if you are creating new prefetcher right after you stop the previous one. Although the stop methods will try to cancel these download tasks in the current main runloop (I assume you are trying to stop and recreate them in main thread), the download task finishing callback will arrive at the next main run loop, so it could cause a problem.

**Comment by mihaibulic** [comment] 2016-05-18 17:10
I'll try that.  Would it cause problems if I create hundreds of downloaders over the course of my app's lifecycle?

**Comment by onevcat** [comment] 2016-05-19 01:08
That should be no problem.

**Comment by danhollywells** [comment] 2016-09-02 04:34
I have run into this same issue. Because the start() method captures the initial X Resources by index and ships them off to startPrefetchingResource() and that methods recursive behavior, you can end up in a state where all the items have been processed but the initial X resources will get double processed because they were captured in the for loop in the start() method and again in the recursion of the startPrefetchingResource(). So if during the prefetch you get into this state and you call stop() you will end up with an unbalanced Range when sorting out the failedResources. I've submitted a pull request #422 with a fix where i've eliminated the use of the manually incremented requestedCount.

**Comment by onevcat** [comment] 2016-09-14 04:11
Should be fixed. Thanks all!

**Closed by onevcat** 2016-09-14 04:11 UTC
Labels: notsure
