### ISSUE TITLE
RoundCornerImageProcessor yields rounded image with square border randomly

### ISSUE THREAD

**Issue by jhoughjr** [onevcat/Kingfisher#1188] opened 2019-05-18 01:42 UTC
I'm not sure of the repro steps as it is random.  I noticed it first on a clients machine.
Then some random time later it occurred for the first time for me.

**Comment by onevcat** [comment] 2019-05-21 13:03
Hi, thank you.

It is the first time we receive such a report. 

We cannot investigate it unless you can provide more information, like a screenshot or some steps to reproduce it. (Or maybe it just happens for a certain image? If it's this case, we need that image.)

For now, since it is not clear what and how to continue, I will close it. Feel free to reopen it if you have more about this issue.

**Closed by onevcat** 2019-05-21 13:03 UTC
