### ISSUE TITLE
iOS 15 crash

### ISSUE THREAD

**Issue by olegtatarciuc** [onevcat/Kingfisher#1837] opened 2021-10-07 11:44 UTC
### Issue Description
Inside XCode's Organizer, I discovered crashes happening on 6 devices which have iOS 15 only.
It gives me the exact line of code which crashes and the stack trace.

<img width="1762" alt="image" src="https://user-images.githubusercontent.com/48445116/136377679-b9162556-4bf6-4f4a-9de0-8b0f97543e8b.png">

**Comment by onevcat** [comment] 2021-10-16 14:08
@timstudt Your issue should not be related to this. If you are using SwiftUI, it is related to #1849 and was fix in 7.1.1.

**Comment by onevcat** [comment] 2021-10-16 14:19
@olegtatarciuc The `path` of `URL` is marked as `String` so it won't be `nil`. But it is still possible the path is not a valid one..I will check if I can reproduce it in some edge cases and give a fix.

**Comment by onevcat** [comment] 2021-10-16 14:41
Ummm.. I cannot reproduce this with all combinations I can think out (empty string, a string containing strange character, a string pointing outside of the sandbox, etc), but none of them can produce a crash to me.

@olegtatarciuc Is there any other information from this crash? Say, does it only happen on a certain type of device or system version? Did you set any special config for the disk cache? And I also wonder what the "warning mark" is saying on the right of "Thread 0" in the crash stack.

**Comment by onevcat** [comment] 2021-12-16 14:26
For the original crash in `stat64`, it is really hard to say what is going on. Since it is not likely we can have a fix in the level of Kingfisher, I am going to close this for now unless there are more similar report received.

**Closed by onevcat** 2021-12-16 14:26 UTC

**Comment by rdu-mega** [comment] 2023-11-03 07:03
Any luck on this issue? In my case this is happening because of low memory warning.
