### ISSUE TITLE
[!] Unable to read the license file

### ISSUE THREAD

**Issue by MoElnaggar14** [onevcat/Kingfisher#1077] opened 2018-12-20 17:33 UTC
- [x] I have read the [wiki page](https://github.com/onevcat/Kingfisher/wiki) and [cheat sheet](https://github.com/onevcat/Kingfisher/wiki/Cheat-Sheet), but there is no information I need.

### Issue Description
when make pod install for Kingfisher, this warning appear
[!] Unable to read the license file `LICENSE` for the spec `Kingfisher (5.0.1)`

**Comment by onevcat** [comment] 2018-12-21 00:47
Not sure why, but we wrote the license file correctly in the podspec. So I guess it should be a CocoaPods issue.

Dose this help?

> I had this warning and it was fixed by commenting all the pods in the Podfile then running pod install then uncomment them back running pod install. I don't know why but it worked fine.

from https://github.com/realm/SwiftLint/issues/1083

**Comment by onevcat** [comment] 2018-12-21 00:51
And maybe also try this: https://github.com/CocoaPods/CocoaPods/issues/5711#issuecomment-339061898

Before that, I suggest upgrading your CocoaPods first.

Since it is not reproducible and seems likely a CocoaPods issue, I am closing it.

**Closed by onevcat** 2018-12-21 00:51 UTC

**Comment by MoElnaggar14** [comment] 2019-01-08 22:31
issue was solved when install version '5.0', i think you need check license file in version 5.0.1 @onevcat
