### ISSUE TITLE
Placeholder image not working with swift 3

### ISSUE THREAD

**Issue by wieseljonas** [onevcat/Kingfisher#510] opened 2016-11-13 14:16 UTC
Even when setting url to nil it doesn't load why?

    cellImage.kf.setImage(with: nil,
                                      placeholder: #imageLiteral(resourceName: "no photo"),
                                      options: [.transition(.fade(1))],
                                      progressBlock: nil,
                                      completionHandler: nil)

**Comment by onevcat** [comment] 2016-11-14 00:53
It will not work only when set url to `nil` (there should be nothing changed when using an non-nil url)
This might be caused by an internal change of #503.

I will give it a fix to load placeholder for `nil` resource later.

**Comment by onevcat** [comment] 2016-11-14 02:38
Should be fixed in 3.2.1

**Closed by onevcat** 2016-11-14 02:38 UTC
