### ISSUE TITLE
when i use Kingfisher 6.2.1 in a new react-native project，i get some errors

### ISSUE THREAD

**Issue by LittleXu** [onevcat/Kingfisher#1693] opened 2021-04-22 07:14 UTC
![image](https://user-images.githubusercontent.com/15767257/115671506-26ac5600-a37d-11eb-970a-cc9929e10f49.png)

when i remove kingfisher in podfile and pod install, i can run the project successfully

**Comment by onevcat** [comment] 2021-04-22 07:19
I did not use RN myself, so I am not sure how it integrate a Swift library. But it seems that a `libKingfisher.a` is built. These errors indicate the simulator slice (x86_64) is not built when you creating `libKingfisher.a`. I don't think it is what can be solved in Kingfisher, but maybe you need to try to ask it in react native repo or related topics.

Ref for example: https://stackoverflow.com/questions/45550228/react-native-ios-build-failed-undefined-symbols-for-architecture-x86-64

**Comment by onevcat** [comment] 2021-04-22 07:24
Oh..wait. It seems that you cannot find `NetworkUnavailableReason`. What is your Xcode version? Currently Kingfisher only supports Xcode 12, so it would fail is you are trying to link it with an earlier version iOS SDK.

**Comment by LittleXu** [comment] 2021-04-22 07:27
my xcode version is 12.4

**Comment by LittleXu** [comment] 2021-04-22 07:37
i create a new project with swift，and i can use kingfisher now， may be react-native project cause the errors

**Comment by onevcat** [comment] 2021-04-23 01:57
I am closing it since I have no more comment for now.

**Closed by onevcat** 2021-04-23 01:57 UTC

**Comment by pepasibble** [comment] 2021-06-18 23:21
Yes, the problem is that React Native forces people to not use `use_frameworks!` in the Podfile, which seems to break things like this.

I'm currently searching for a solution here.  I've had to resort to using Cocoapods for React Native and Carthage for Kingfisher, all in the same project 😭

**Comment by pepasibble** [comment] 2021-06-19 00:26
Ok, I got this figured out.

Install this plugin for cocoapods: `gem install cocoapods-user-defined-build-types`

Add this to the top of your Podfile:

```
plugin 'cocoapods-user-defined-build-types'
enable_user_defined_build_types!
```

Then specify that Kingfisher needs to be built as a dynamic framework:

```
  pod 'Kingfisher', '6.1.1', :build_type => :dynamic_framework
```

**Comment by jellopyz** [comment] 2021-06-20 10:25
> Ok, I got this figured out.
> 
> Install this plugin for cocoapods: `gem install cocoapods-user-defined-build-types`
> 
> Add this to the top of your Podfile:
> 
> ```
> plugin 'cocoapods-user-defined-build-types'
> enable_user_defined_build_types!
> ```
> 
> Then specify that Kingfisher needs to be built as a dynamic framework:
> 
> ```
>   pod 'Kingfisher', '6.1.1', :build_type => :dynamic_framework
> ```
> 
> run `pod install`
> 
> Now you should be able to just `import Kingfisher` as per usual in the Swift portions of your React Native project.

What about when I used `Kingfisher` as dependency of my private pod. such as `s.depencency = "Kingfisher"`
