### ISSUE TITLE
when does the image download start?

### ISSUE THREAD

**Issue by alexdd55** [onevcat/Kingfisher#19] opened 2015-04-20 09:18 UTC
when i open my app, the avatar image is empty and waits (through async download) for the image.
somehow it takes up to 30 sec until the image is loaded (3kb of size), the reason is not a slow download. 
what triggers this download?
is there a timer that will tell KF to wait for n seconds befor its starts to download?

**Comment by onevcat** [comment] 2015-04-20 09:24
If you are using the UIImageView category, the download would be started in a background thread very soon once you call `kf_setImageWithURL` methods.

There should be no timer or intended delay for it. Does it happen every time?

**Comment by alexdd55** [comment] 2015-04-20 09:37
when i start the app it took about 5 secs to start downloading after everything else is shown.
i experienced longer time yesterday.

when i scroll this doesn't seem to happen, there is no delay on downloading. 

here is what i do.. maybe the problem is on my side ;)

```
if self.kfmanager.cache.isImageCachedForKey(screenname).cached {
			cell.avatar?.image = self.kfmanager.cache.retrieveImageInDiskCacheForKey(screenname)
		} else {
			self.kfmanager.retrieveImageWithURL(avaImgUrl, options: nil, progressBlock: {
				(receivedSize, totalSize) -> () in
				println(receivedSize)
				}, completionHandler: {
					(image, error, imageURL) -> () in
					cell.avatar?.image = image
					self.kfmanager.cache.storeImage(image!, forKey: screenname)
			})
		}
```

**Comment by onevcat** [comment] 2015-04-20 09:52
Hi,

The `retrieveImageWithURL:options:progressBlock:completionHandler:` will try to seek the image in cache with url as the key. If not found, it will begin to download and do cache. That means you are doing seeking and caching twice for every image.

Since you are already checked it with the first line, it is better to just use the `self.kfmanager.downloader` to download it by `downloadImageWithURL` method and cache it in the completion handler in the download method.

But it should not cause the download delay. If it is, it might be something wrong when handling the thread dispatch. I will check and confirm it later. Thanks for the sample code.

**Comment by alexdd55** [comment] 2015-04-20 10:55
Thanks for the hint. Removing the double check, made things (of course) quicker. :+1: 

Funny is, that after opening the app, the first unloaded image still takes around 5-7 seconds (last two test). after that everything is great. images get loaded instantly.

i will keep an eye on it, 
it seems that i might be the only one having this issue, maybe i do something wrong sowmwhere in my code that delays the inital call on the script...?!

**Comment by onevcat** [comment] 2015-04-21 03:52
I will keep an eye on it. If anyone suffers from the same issue, please let me know.

@alexdd55 Is it possible to provide a reproducible demo for it? It will be a great help for finding what happened.

**Comment by htarwara6245** [comment] 2015-06-04 06:20
My car images from tableview stop downloading or not appear when i finished showing the results of 150 so,car total images will be 150..i dont know why.My car images stop showing after 150 results.I have a table view which show car images and records per table cell.Here is my code,any help?

http://puu.sh/ibQrT/38f9c92f75.png

**Comment by onevcat** [comment] 2015-06-04 09:29
Hi, @htarwara6245 
Could you describe your problem in more detail? And may I know what does the `&w=150` mean in your url?

**Comment by htarwara6245** [comment] 2015-06-04 10:10
"&w=150" means i download the photo that are come with width=150,so it will be lower size.

**Comment by onevcat** [comment] 2015-06-05 02:17
@htarwara6245 

The code snippet posted above seems good to me. It might be somewhere else caused that issue.

(And since the default cache used in Kingfisher is the `KingfisherManager.sharedManager.cache`, so there is no necessary to set the optionsInfo again. But it should not the reason for your issue.)

**Comment by onevcat** [comment] 2015-08-06 15:27
Seems there is no other report for this. So I guess it is an app project issue instead of .Kingfisher. I am closing this.

**Closed by onevcat** 2015-08-06 15:27 UTC
Labels: question
