### ISSUE TITLE
Image get Rotated after applying RoundCornerImageProcessor

### ISSUE THREAD

**Issue by indrajitsinh** [onevcat/Kingfisher#564] opened 2017-01-18 14:47 UTC
if i load the image without applying RoundCornerImageProcessor the image will load perfectly but when i apply RoundCornerImageProcessor it will rotate the image.

**my code** 
```swift
 let modifier = AnyModifier { request in
           var r = request
           if let token = getAuthToken() {
                  r.setValue(token, forHTTPHeaderField: "AuthToken")
           }
                            
          return r
 }
                        
let url = URL(string: "http://xyz.com/images/mycoolimage.jpg")
let processor = RoundCornerImageProcessor(cornerRadius: 60)
self.userProfileImage.kf.setImage(with: url, placeholder: UIImage(named: "ico-menu-user-default"), options: [.requestModifier(modifier),.processor(processor)])

```
**following is the screen shot**

![image processing bug](https://cloud.githubusercontent.com/assets/11308777/22068285/9617dad8-ddba-11e6-99a7-82b6a349dd6b.jpeg)

does i am doing something wrong or it's a bug ?

**Comment by onevcat** [comment] 2017-01-19 01:24
Maybe related to #535 

However, I cannot reproduce this issue for an image with non-top orientation exif. The round corner processor is doing nothing on the image orientation. So it is a bit weird.

Can you upload this image in this issue? So I can take a look at it.

And for a quick "workaround", maybe you could follow the `NormalizingProcessor` way to see whether it could work or not. (But it should not be necessary.)

**Comment by onevcat** [comment] 2017-01-30 02:31
Since there is no additional comment, I will close it now. If there are any other similar cases, feel free to reopen this one or just create a new issue.

**Closed by onevcat** 2017-01-30 02:31 UTC
